### ISSUE TITLE
REST API Needed for batch download of article data (via JSON)

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/Master#937]
At the moment the TM 4.0 Node server needs to make one JSON call per TM article on the DB which is not efficient or scalable.

We need a better way to get data from TM 3.5, and this could be a simple new WebService that packages (and maybe even zips) a number of TM articles (in JSON format) so that they can be easily imported from other servers

The retrieval of library structure is good at the moment. What is needed is a good/fast solution to get the articles. 

This is something @michaelhidalgo could do, since it is a variation of the other methods he has been adding

**Comment by DinisCruz** [comment]
this is not needed any more

**Comment by roman87** [comment]
Agreed. Closing
