### ISSUE TITLE
Password reset/Change Password does not survive server restart in 3.6

### ISSUE THREAD

**Issue by roman87** [TeamMentor/Master#943]
When you change your password or reset your password, if the server is restarted the new password no longer works, but the old one does. Seems like the write is not happening to the actual User file.

**Comment by michaelhidalgo** [comment]
Good catch!.
I'm doing some debugging to find the root cause.

**Comment by roman87** [comment]
Looks like any config change does not survive the restart. Including secretData Config

**Comment by roman87** [comment]
Looks like the problem was between the keyboard and the chair. I forgot to add the AppPool permissions for the Library_Data directory. 
Just shows how badly we need the installer :)
