### ISSUE TITLE
where do we put 4.0 content related questions and issues

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/Master#944]
These are issues that only affect the content that exposed/provided by the new 4.0 design

for example, this is what I get when searching for 'Model'

![image](https://cloud.githubusercontent.com/assets/656739/5943607/4a58fd78-a718-11e4-8228-320383cd7ac8.png)

which are basically 5 very similar articles 

I don't think this repo or TM Master are good places. Maybe on https://github.com/TMContent/Lib_UNO ?

**Comment by roman87** [comment]
I will check with @SergeTruth

**Comment by roman87** [comment]
After discussion with @SergeTruth  and @SandraPaivaSI  it was decided that content related issues should be put in https://github.com/TMContent/Lib_UNO/issues
Serge will come up with a labeling system, borrowing from ours and Sandra's,that fits his process.

**Comment by roman87** [comment]
Closing this as the question was answered.

**Comment by DinisCruz** [comment]
Humm... I just connected the dots, and realised that that repo is private, which means that it will be harder for others to contribute and collaborate.

Question: if a user/tester/client does not have access to that repo, where should they post too?

**Comment by roman87** [comment]
There are couple of things to this. First, we need to separate client/internal requests and comments and our workflow. Our workflow has certain guidelines and expectations that outside users will not follow. Second we need to vet outside requests for usefulness. Most mature organizations call it a customer service system :)  I don't think we are at that point yet. However I think that outside suggestions need to come via email, or some other system not tied to our workflow.

**Comment by DinisCruz** [comment]
Well I think having a public repo helps a lot new participants (as we can see on the TM_4_0_Design repo)

**Comment by roman87** [comment]
I think on the contrary. Discussions we are having on the TM_4_0_Design are negatively impacting the workflow. Don't get me wrong, these are great discussions, they just don't belong in our workarea. They are of two types - forum based discussions and "customer" requests that we need to track. Nether ones are by themselves actionable work units that we can use in our workflow. They need to be translated into such and tracked separately.

**Comment by DinisCruz** [comment]
Then we have to agree to disagree on this one

**Comment by roman87** [comment]
Github is a tool. Github issues is a tool. Lets not get entrapped with the law of the instrument :)
