### ISSUE TITLE
As a user when viewing an article list, I should see an intuative icon next to the article titile, such that I can quickly determine some article metadata and article position on the list

### ISSUE THREAD

**Issue by roman87** [TeamMentor/Master#950]
- [x] https://github.com/TeamMentor/TM_4_0_Design/issues/574
- [x] https://github.com/TeamMentor/TM_4_0_Design/issues/568
- [x] https://github.com/TeamMentor/TM_4_0_Design/issues/577

**Comment by luchia** [comment]
These have all been completed from my side of things. @DinisCruz now has control of these issues.

**Comment by roman87** [comment]
I think they are all back in your court @luchia

**Comment by roman87** [comment]
All done. Closing
